import assert from 'node:assert/strict';
import test from 'node:test';
import ts from 'typescript';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'plot3k-tests-'));
for(const file of ['planner','plot3k'])fs.writeFileSync(path.join(temp,file+'.js'),ts.transpileModule(fs.readFileSync(new URL('../app/'+file+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText);
fs.copyFileSync(new URL('../app/seed-catalog.json',import.meta.url),path.join(temp,'seed-catalog.json'));
const require=createRequire(import.meta.url),{initialPlan,SEEDS,rowLayout,points,makeBlock,blockErrors,validatePlan,shareEncode,shareDecode}=require(path.join(temp,'plot3k.js'));
test('invoices reconcile to 28 entries and 27 unique purchased plants',()=>{const bought=SEEDS.filter(c=>c.packets);assert.equal(bought.length,27);assert.equal(bought.reduce((n,c)=>n+c.packets,0),28);assert.equal(bought.find(c=>c.id==='echinacea').sources.length,2);assert.equal(bought.filter(c=>c.method==='Tuber').length,2);assert(bought.every(c=>c.sources.length));});
test('rows use independent plant and row pitch, all points stay inside footprint',()=>{const b={x:0,y:0,width:100,length:100,rowSpacing:50,spacing:10,direction:'length'};assert.deepEqual(rowLayout(b),{rows:2,perRow:10,count:20});assert(points(b).every(p=>p.x>=25&&p.x<=75&&p.y>=5&&p.y<=95));assert.deepEqual(rowLayout({...b,direction:'across',length:60}),{rows:1,perRow:10,count:10});});
test('proposals preserve paths and do not collide, purchased tubers produce one position',()=>{const p=structuredClone(initialPlan);for(const id of ['cafe','teddy','echinacea','green-wizard','lime','salmon','peach','beetroot','cherokee','roma','holy-basil','chives']){const b=makeBlock(id,p);assert(b, id+' fits');assert.deepEqual(blockErrors(b,p),[]);p.blocks.push(b);if(['cafe','teddy'].includes(id))assert.equal(rowLayout(b).count,1);}assert.equal(p.blocks.length,12);assert.deepEqual(validatePlan(p),p);});
test('overlap, out of bounds and impossible spacing are surfaced',()=>{const p=structuredClone(initialPlan);const b=makeBlock('lime',p);p.blocks.push(b);assert(blockErrors({...b,id:'copy'},p).includes('Overlaps another active block'));assert(blockErrors({...b,x:100},p).includes('Outside the growing bed'));assert(blockErrors({...b,rowSpacing:200},p).includes('No plants fit at this spacing'));});
test('snapshot round trip preserves Unicode and row completion; malformed imports fail',()=>{const p=structuredClone(initialPlan);const b=makeBlock('lime',p);p.blocks=[{...b,notes:'Partner’s 🌱 row',doneRows:[0]}];assert.deepEqual(shareDecode(shareEncode(p)),p);assert.throws(()=>validatePlan({...p,version:2}));assert.throws(()=>validatePlan({...p,blocks:[{...b,spacing:0}]}));assert.throws(()=>validatePlan({...p,blocks:[{...b,cropId:'missing'}]}));});
