'use client';
import {useEffect,useRef,useState} from 'react';
import {BY_ID,SEEDS,initialPlan,bedWidth,rowLayout,points,blockErrors,makeBlock,validatePlan,shareEncode,shareDecode,type Plan,type Block,type Seed} from './plot3k';
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const KEY='plot-3k-plan-v3';
const colours=['#a75a70','#78863c','#cb8750','#8370a4','#bb647e','#457956','#9a6b47','#477b80'];
const color=(id:string)=>colours[SEEDS.findIndex(c=>c.id===id)%colours.length];
const stamp=()=>new Date().toISOString();
function starter(){const p=structuredClone(initialPlan);for(const id of ['cafe','teddy','echinacea','green-wizard','lime','salmon','peach','beetroot','cherokee','roma','holy-basil','chives']){const b=makeBlock(id,p);if(b)p.blocks.push(b);}return p;}
function NumberField({label,value,onChange,min=0,max=2000}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number}){return <label>{label}<input type="number" value={value} min={min} max={max} step={5} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=min&&n<=max)onChange(n);}}/></label>}
function GrowGuide({seed}:{seed:Seed}){return <div className="grow-guide"><span className="eyebrow">Growing instructions</span><h3>{seed.name}</h3><dl><div><dt>Life cycle</dt><dd>{seed.life}</dd></div><div><dt>Sow in Melbourne</dt><dd>{seed.months.map(m=>MONTHS[m-1]).join(' · ')}</dd></div><div><dt>Start by</dt><dd>{seed.method}</dd></div><div><dt>Sowing depth</dt><dd>{seed.depth}</dd></div><div><dt>Germination</dt><dd>{seed.germination}</dd></div><div><dt>Plant / row spacing</dt><dd>{seed.spacing} / {seed.rowSpacing} cm</dd></div><div><dt>Mature height</dt><dd>Up to {seed.height} cm</dd></div><div><dt>Harvest / flowers</dt><dd>{seed.days}{seed.days!=='Not specified'?' days (approx.)':''}</dd></div><div><dt>Position</dt><dd>{seed.position}</dd></div></dl><p>{seed.notes}</p><p className="fine">Where the supplier gives only plant spacing, the grid uses the same distance between rows. Calendar windows are for sowing, not a guarantee of outdoor planting conditions.</p>{seed.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.supplier} growing guide ↗</a>)}<small>Checked {seed.checked}</small></div>}
export default function Page(){
 const [plan,setPlan]=useState<Plan>(initialPlan),[ready,setReady]=useState(false),[selected,setSelected]=useState(''),[tab,setTab]=useState('plan'),[zoom,setZoom]=useState(1),[query,setQuery]=useState(''),[filter,setFilter]=useState('purchased'),[month,setMonth]=useState(9),[onlySeason,setOnlySeason]=useState(false),[notice,setNotice]=useState(''),[shared,setShared]=useState(false),[shareUrl,setShareUrl]=useState(''),[history,setHistory]=useState<Plan[]>([]),[guide,setGuide]=useState<string>(''),[saved,setSaved]=useState(''),[legacy,setLegacy]=useState(false),[storageSafe,setStorageSafe]=useState(true),[snapshotKey,setSnapshotKey]=useState('');
 const modal=useRef<HTMLElement>(null);
 useEffect(()=>{if(!guide)return;const previous=document.activeElement as HTMLElement;const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')setGuide('');if(e.key==='Tab'){const focus=modal.current?.querySelectorAll<HTMLElement>('button,a,input,select,textarea,[tabindex="0"]');if(!focus?.length)return;const first=focus[0],last=focus[focus.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus();};},[guide]);
 const file=useRef<HTMLInputElement>(null);const inspector=useRef<HTMLElement>(null);
 useEffect(()=>{try{const hash=new URLSearchParams(location.hash.slice(1)).get('plan');if(hash){const original=shareDecode(hash);const key='plot-3k-snapshot-'+hash;setSnapshotKey(key);const savedSnapshot=localStorage.getItem(key);setPlan(savedSnapshot?validatePlan(JSON.parse(savedSnapshot)):original);setShared(true);setNotice('Shared snapshot. Changes stay on this device until you share a new copy.');}else{const saved=localStorage.getItem(KEY);setPlan(saved?validatePlan(JSON.parse(saved)):starter());}setLegacy(!!localStorage.getItem('plot-3p-plan-v2'));setMonth(Number(new Intl.DateTimeFormat('en',{month:'numeric',timeZone:'Australia/Melbourne'}).format(new Date())));}catch{setStorageSafe(false);setNotice('Could not read the saved/shared plan. Your previous data has not been changed. Import a valid backup to continue.');setPlan(initialPlan);}setReady(true);},[]);
 useEffect(()=>{if(!ready||!storageSafe)return;try{if(!shared||snapshotKey){localStorage.setItem(shared?snapshotKey:KEY,JSON.stringify(plan));setSaved('Saved on this device');}}catch{setSaved('Not saved — export a backup');}},[plan,ready,shared,storageSafe,snapshotKey]);
 function commit(p:Plan){setHistory(h=>[...h.slice(-29),plan]);setPlan({...p,updated:stamp()});setShareUrl('');}
 function updateBlock(patch:Partial<Block>){if(!block)return;const structural=['x','y','width','length','spacing','rowSpacing','side','direction','cropId'];if(block.locked&&structural.some(k=>k in patch)){setNotice('Unlock this block before changing its layout.');return;}const reset=structural.some(k=>k in patch);commit({...plan,blocks:plan.blocks.map(b=>b.id===block.id?{...b,...patch,...(reset?{doneRows:[]}: {})}:b)});}
 function add(id:string){const b=makeBlock(id,plan);if(!b){setNotice('No clear space for this block. Resize an existing block or mark a harvested seasonal block finished first.');return;}commit({...plan,blocks:[...plan.blocks,b]});setSelected(b.id);setTab('plan');setNotice('Added a proposed block. Choose its date and review the growing instructions before sowing.');}
 function download(data:unknown,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 async function share(){const url=location.origin+location.pathname+'#plan='+shareEncode(plan);setShareUrl(url);try{await navigator.clipboard.writeText(url);setNotice('Snapshot link copied. Send it to your partner; share again after later changes.');}catch{setNotice('Copy the snapshot link below.');}}
 const block=plan.blocks.find(b=>b.id===selected),seed=block?BY_ID[block.cropId]:null,bw=bedWidth(plan),active=plan.blocks.filter(b=>b.status!=='finished'),count=active.reduce((s,b)=>s+rowLayout(b).count,0);
 const errors=active.flatMap(b=>blockErrors(b,plan).map(e=>({b,e})));const seeds=SEEDS.filter(c=>(filter==='all'||filter==='purchased'&&c.packets>0||filter==='flowers'&&c.side==='flowers'||filter==='food'&&c.side==='food'||filter==='perennial'&&/perennial/i.test(c.life))&&c.name.toLowerCase().includes(query.toLowerCase())&&(!onlySeason||c.months.includes(month)));
 const originX=65,originY=60,mapWidth=plan.plot.width+130,mapHeight=plan.plot.length+125;
 function select(id:string){setSelected(id);if(window.innerWidth<900)setTimeout(()=>inspector.current?.scrollIntoView({behavior:'smooth',block:'start'}),100);}
 const warnings=(b:Block)=>{const c=BY_ID[b.cropId];return [...blockErrors(b,plan),...(b.spacing<c.spacing||b.rowSpacing<c.rowSpacing?['Closer than supplier spacing; review airflow and mature growth.']:[]),...((b.side===plan.plot.flowers)!==(c.side==='flowers')?['This crop is on the other half of the plot.']:[]),...(c.height>=100&&b.y<plan.plot.length/2?['Tall planting near the north end may shade crops to its south.']:[]),...(c.method==='Tuber'&&plan.blocks.filter(o=>o.cropId===c.id&&o.status!=='finished').reduce((s,o)=>s+rowLayout(o).count,0)>1?['Only one tuber of this variety was purchased.']:[])];};
 return <main><header className="topbar"><div className="brand"><span className="brand-mark">3K</span><div><h1>The veggie patch</h1><p>CERES · Plot 3K · Melbourne</p></div></div><div className="top-actions"><span className="save-state">{shared?'Shared snapshot':saved}</span><button onClick={()=>window.print()}>Print plan</button><button className="primary" onClick={share}>Share with partner ↗</button></div></header>
 <nav aria-label="Planner views">{[['plan','Planting plan'],['seeds','Seed collection'],['jobs','In the garden'],['setup','Plot & backups']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {notice&&<div className="notice" role="status"><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}>×</button></div>}{shareUrl&&<div className="share-box"><label>Partner link · a snapshot, not live sync<input value={shareUrl} readOnly onFocus={e=>e.target.select()}/></label></div>}
 <section className="intro"><div><span className="eyebrow">{tab==='plan'?'A place for every row':tab==='seeds'?'Your September seed orders':tab==='jobs'?'Take the plan outside':'Measurements & care of your plan'}</span><h2>{tab==='plan'?'Plan the planting.':tab==='seeds'?'The seed collection.':tab==='jobs'?'In the garden.':'Your new plot.'}</h2></div><div className="stats"><span><strong>{(plan.plot.width*plan.plot.length/10000).toFixed(2)}</strong>m² plot</span><span><strong>{active.length}</strong>active blocks</span><span><strong>{count}</strong>planting positions</span></div></section>
 {!ready?<p>Opening your planting plan…</p>:<>
 {tab==='plan'&&<div className="workspace"><section className="map-panel"><div className="panel-head"><div><h3>Plot 3K</h3><p>North up · {plan.plot.length/100} × {plan.plot.width/100} m</p></div><div className="zoom"><button aria-label="Zoom out" disabled={zoom<=.75} onClick={()=>setZoom(z=>Math.max(.75,z-.25))}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" disabled={zoom>=3} onClick={()=>setZoom(z=>Math.min(3,z+.25))}>+</button><button onClick={()=>setZoom(1)}>Fit</button></div></div>
 <div className="map-scroll"><svg role="img" aria-label="Scaled planting map of plot 3K. North is at the top. Select a labelled block to edit its rows." viewBox={`0 0 ${mapWidth} ${mapHeight}`} style={{width:`${zoom*350}px`,maxWidth:zoom<=1?'100%':undefined}}><defs><pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M 10 0 L 0 0 0 10" fill="none" stroke="#b7c4b0" strokeWidth=".35"/></pattern><pattern id="plank" width="7" height="30" patternUnits="userSpaceOnUse"><path d="M 2 0 V 30 M 5 10 V 24" stroke="#b7a385" strokeWidth=".6"/></pattern></defs>
 <text x={mapWidth/2} y="20" textAnchor="middle" className="map-heading">↑ N · NORTHERN END</text><text x={originX+bw/2} y="43" textAnchor="middle" className="bed-title">{plan.plot.flowers==='west'?'CUT FLOWERS':'VEG & HERBS'}</text><text x={originX+bw+plan.plot.path+bw/2} y="43" textAnchor="middle" className="bed-title">{plan.plot.flowers==='east'?'CUT FLOWERS':'VEG & HERBS'}</text>
 {['west','east'].map(side=><g key={side}><rect x={originX+(side==='east'?bw+plan.plot.path:0)} y={originY} width={bw} height={plan.plot.length} fill="#e4e9da" stroke="#556848" strokeWidth="2"/><rect x={originX+(side==='east'?bw+plan.plot.path:0)} y={originY} width={bw} height={plan.plot.length} fill="url(#grid)"/></g>)}
 <rect x={originX+bw} y={originY} width={plan.plot.path} height={plan.plot.length} fill="#d5c3a5"/><rect x={originX+bw} y={originY} width={plan.plot.path} height={plan.plot.length} fill="url(#plank)"/>
 <text transform={`translate(${originX+bw+plan.plot.path/2},${originY+plan.plot.length/2}) rotate(-90)`} textAnchor="middle" className="path-label">CENTRAL PLANK · {plan.plot.path} CM</text>
 {Array.from({length:Math.floor(plan.plot.length/100)+1},(_,i)=><g key={i}><line x1={originX-8} x2={originX} y1={originY+i*100} y2={originY+i*100} stroke="#68745f"/><text x={originX-12} y={originY+i*100+4} textAnchor="end" className="measure">{i} m</text></g>)}
 {active.map(b=>{const c=BY_ID[b.cropId],offset=originX+(b.side==='east'?bw+plan.plot.path:0),sel=selected===b.id,layout=rowLayout(b),idx=plan.blocks.indexOf(b)+1;return <g key={b.id} role="button" tabIndex={0} aria-label={`Block ${idx}, ${c.name}, ${layout.rows} rows of ${layout.perRow}`} onClick={()=>select(b.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(b.id);}}} className="map-block"><title>{c.name}: {layout.rows} rows × {layout.perRow}. {b.permanent?'Permanent.':''}</title><rect x={offset+b.x} y={originY+b.y} width={b.width} height={b.length} rx="2" fill={color(c.id)} fillOpacity=".22" stroke={sel?'#172f20':color(c.id)} strokeWidth={sel?2.4:1} strokeDasharray={b.permanent?'4 2':undefined}/>{points(b).slice(0,2500).map((p,i)=><circle key={i} cx={offset+p.x} cy={originY+p.y} r={Math.min(3.3,b.spacing*.16)} fill={color(c.id)} opacity={b.doneRows.includes(p.row)?.3:.85}/>)}<rect x={offset+b.x+2} y={originY+b.y+2} width={Math.min(30,b.width-4)} height="13" rx="2" fill={sel?'#172f20':'#fff'}/><text x={offset+b.x+6} y={originY+b.y+11} fill={sel?'#fff':'#172f20'} className="block-label">{b.side==='west'?'W':'E'}{idx}{b.permanent?' P':''}</text></g>})}
 <text x={mapWidth/2} y={originY+plan.plot.length+24} textAnchor="middle" className="map-heading">SOUTHERN END</text><line x1={originX} x2={originX+100} y1={mapHeight-20} y2={mapHeight-20} stroke="#172f20" strokeWidth="2"/><text x={originX+110} y={mapHeight-16} className="measure">1 metre</text></svg></div><div className="print-legend">{active.map(b=><p key={b.id}><strong>{b.side==='west'?'W':'E'}{plan.blocks.indexOf(b)+1}: {BY_ID[b.cropId].name}</strong> — {rowLayout(b).rows} rows × {rowLayout(b).perRow}; plants {b.spacing} cm, rows {b.rowSpacing} cm. {b.date||'Date not set'}. {b.notes}</p>)}</div><div className="map-foot"><span>Each dot = one final plant or chive clump</span><span>Dashed border = permanent block</span></div><p className="fine">20 cm plank width is provisional. Grid: 10 cm. Tap a block; zoom for planting detail. Labels match the block list.</p></section>
 <aside ref={inspector} className="inspector"><div className="panel-head"><h3>{block?'Edit planting block':'Planting blocks'}</h3><button disabled={!history.length} onClick={()=>{setPlan(history[history.length-1]);setHistory(h=>h.slice(0,-1));}}>↶ Undo</button></div>
 {block&&seed?<><div className="selected-heading"><span className="eyebrow">{block.side==='west'?'W':'E'}{plan.blocks.indexOf(block)+1} · {block.side} bed</span><h3>{seed.name}</h3><button className="text-button" onClick={()=>setSelected('')}>← All blocks</button></div><div className="row-summary"><strong>{rowLayout(block).rows} rows × {rowLayout(block).perRow}</strong><span>{rowLayout(block).count} planting positions</span></div>
 <div className="form-grid"><label>Bed<select value={block.side} disabled={block.locked} onChange={e=>updateBlock({side:e.target.value as Block['side']})}><option value="west">West</option><option value="east">East</option></select></label><label>Rows run<select value={block.direction} disabled={block.locked} onChange={e=>updateBlock({direction:e.target.value as Block['direction']})}><option value="length">North–south</option><option value="across">East–west</option></select></label></div>
 <fieldset disabled={block.locked}><legend>Block measurements · cm</legend><div className="form-grid"><NumberField label="From bed’s west edge" value={block.x} max={bw} onChange={x=>updateBlock({x})}/><NumberField label="From north end" value={block.y} max={plan.plot.length} onChange={y=>updateBlock({y})}/><NumberField label="Block width" value={block.width} min={5} max={bw} onChange={width=>updateBlock({width})}/><NumberField label="Block length" value={block.length} min={5} max={plan.plot.length} onChange={length=>updateBlock({length})}/><NumberField label="Plants apart" value={block.spacing} min={5} max={200} onChange={spacing=>updateBlock({spacing})}/><NumberField label="Rows apart" value={block.rowSpacing} min={5} max={200} onChange={rowSpacing=>updateBlock({rowSpacing})}/></div></fieldset>
 <p className="fine">Start the first row {block.rowSpacing/2} cm inside the block; first plant {block.spacing/2} cm from its end. All distances are centre to centre.</p>
 {warnings(block).map(w=><p className="warning" key={w}>{w}</p>)}
 <div className="form-grid"><label>Status<select value={block.status} onChange={e=>updateBlock({status:e.target.value as Block['status']})}><option value="planned">Planned</option><option value="sown">Sown in trays</option><option value="planted">Planted / direct sown</option><option value="finished">Finished / cleared</option></select></label><label>Target outdoor date<input type="date" value={block.date} onChange={e=>updateBlock({date:e.target.value})}/></label></div>
 <label className="check"><input type="checkbox" checked={block.permanent} onChange={e=>updateBlock({permanent:e.target.checked})}/>Reserve across seasons</label><label className="check"><input type="checkbox" checked={block.locked} onChange={e=>updateBlock({locked:e.target.checked})}/>Lock this layout</label><label>Planting notes<textarea value={block.notes} maxLength={3000} onChange={e=>updateBlock({notes:e.target.value})} placeholder="E.g. label the row and water after planting"/></label><div className="button-row"><button onClick={()=>setGuide(seed.id)}>Growing guide</button><button className="danger" disabled={block.locked} onClick={()=>{commit({...plan,blocks:plan.blocks.filter(b=>b.id!==block.id)});setSelected('');}}>Remove block</button></div></>:<><p className="fine">Choose a block to adjust its size, row spacing and planting date. Add varieties from your seed collection.</p><button className="primary full" onClick={()=>setTab('seeds')}>+ Add a planting block</button><div className="block-list">{plan.blocks.map((b,i)=><button key={b.id} onClick={()=>setSelected(b.id)}><span className="block-id" style={{background:color(b.cropId)}}>{b.side==='west'?'W':'E'}{i+1}</span><span><strong>{BY_ID[b.cropId].name}</strong><small>{rowLayout(b).rows} rows × {rowLayout(b).perRow} · {b.permanent?'Permanent':b.status}</small></span><span>›</span></button>)}</div></>}
 </aside></div>}
 {tab==='seeds'&&<section><div className="collection-tools"><label className="search">Find a plant<input placeholder="Search varieties…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Collection<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="purchased">Purchased · 27 varieties</option><option value="flowers">Flowers</option><option value="food">Vegetables & herbs</option><option value="perennial">Perennials</option><option value="all">All, including existing library</option></select></label><label>Sowing month<select value={month} onChange={e=>setMonth(+e.target.value)}>{MONTHS.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label className="check"><input type="checkbox" checked={onlySeason} onChange={e=>setOnlySeason(e.target.checked)}/>Suitable to sow this month</label></div><p className="fine">28 purchased entries → 27 varieties. Echinacea pallida combines two packets. Equipment is excluded. Packet quantities are inventory, not a planting target. Keep unallocated varieties for later successions.</p><div className="seed-grid">{seeds.map(c=><article className="seed-card" key={c.id}><div className="seed-stripe" style={{background:color(c.id)}}/><span className="eyebrow">{c.side==='flowers'?'Cut flowers':'Veg & herbs'} · {c.life}</span><h3>{c.name}</h3><p>{c.spacing} cm plants · {c.rowSpacing} cm rows<br/>Up to {c.height} cm tall</p><div className="tags"><span>{c.packets?`${c.packets} packet${c.packets>1?'s':''}${c.method==='Tuber'?' / tuber':''}`:'General library'}</span><span>{c.months.includes(month)?`${MONTHS[month-1]} sowing window`:'Plan for later'}</span></div>{c.seedCount!=null&&<small>{c.seedCount} {c.method==='Tuber'?'tuber purchased':'seeds on invoice'}</small>}{c.id==='echinacea'&&<small>40 seeds from VFGS + one Seed Collection packet</small>}<div className="button-row"><button onClick={()=>setGuide(c.id)}>Growing guide</button><button onClick={()=>add(c.id)}>+ Add block</button></div></article>)}</div>{!seeds.length&&<p>No varieties match these filters.</p>}</section>}
 {tab==='jobs'&&<section className="garden-view"><div className="notice">Mark rows as you plant them. Each row uses the block’s final plant spacing. Changes are saved on this device; share a new snapshot to pass them on.</div>{!active.length&&<p>Add a block in the seed collection to create your planting instructions.</p>}{[...active].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).map(b=>{const c=BY_ID[b.cropId],r=rowLayout(b),idx=plan.blocks.indexOf(b)+1;return <article className="job" key={b.id}><div className="job-heading"><span className="block-id" style={{background:color(c.id)}}>{b.side==='west'?'W':'E'}{idx}</span><div><h3>{c.name}</h3><p>{b.date?`Target outdoor date: ${b.date}`:'Outdoor date not set'} · {b.status}</p></div><button onClick={()=>{setSelected(b.id);setTab('plan');}}>Show block</button></div><p><strong>{r.rows} rows of {r.perRow}</strong> · {b.spacing} cm between plants · {b.rowSpacing} cm between rows</p><p>In the {b.side} bed, measure {b.y} cm from the north end and {b.x} cm from the bed’s west edge. Mark a {b.width} × {b.length} cm block. Rows run {b.direction==='length'?'north–south':'east–west'}.</p><p>First row: {b.rowSpacing/2} cm in from the block edge. First plant: {b.spacing/2} cm along the row. Sow {c.depth.toLowerCase()} · {c.method.toLowerCase()}.</p>{!c.months.includes(month)&&<p className="warning">Outside the supplier’s {MONTHS[month-1]} sowing window. Follow the target date and check conditions before planting.</p>}{warnings(b).map(w=><p className="warning" key={w}>{w}</p>)}{b.notes&&<p className="job-note">{b.notes}</p>}<div className="row-checks">{Array.from({length:r.rows},(_,i)=><label className="check" key={i}><input type="checkbox" checked={b.doneRows.includes(i)} onChange={e=>commit({...plan,blocks:plan.blocks.map(o=>o.id===b.id?{...o,doneRows:e.target.checked?[...o.doneRows,i]:o.doneRows.filter(n=>n!==i)}:o)})}/>Row {i+1} · {r.perRow} plants</label>)}</div><button onClick={()=>setGuide(c.id)}>Read growing guide</button></article>})}<label>Notes for the garden<textarea value={plan.notes} maxLength={10000} onChange={e=>commit({...plan,notes:e.target.value})} placeholder="What to water, which trays are ready, what to leave for later…"/></label></section>}
 {tab==='setup'&&<div className="setup-grid"><section className="card"><h3>5.4 metres, north to south.</h3><p>Two equal growing beds, divided by the existing lengthwise plank. Full northern exposure with very little external shade, as you described.</p><div className="form-grid"><NumberField label="North–south length · cm" value={plan.plot.length} min={100} onChange={length=>commit({...plan,plot:{...plan.plot,length}})}/><NumberField label="East–west width · cm" value={plan.plot.width} min={100} max={1000} onChange={width=>commit({...plan,plot:{...plan.plot,width}})}/><NumberField label="Plank width · cm (estimate)" value={plan.plot.path} min={5} max={Math.min(150,plan.plot.width-40)} onChange={path=>commit({...plan,plot:{...plan.plot,path}})}/></div><p>Each growing half: {(bw/100).toFixed(2)} m wide × {plan.plot.length/100} m long.</p><button onClick={()=>commit({...plan,plot:{...plan.plot,flowers:plan.plot.flowers==='west'?'east':'west'},blocks:plan.blocks.map(b=>({...b,side:b.side==='west'?'east':'west',x:bw-b.x-b.width}))})}>Swap flower and vegetable halves</button><p className="fine">Flowers start on the west as a proposal. Measure the actual plank; there is no universal standard width. Changing dimensions flags blocks that need moving.</p>{errors.map(({b,e},i)=><p className="warning" key={i}>{BY_ID[b.cropId].name}: {e}</p>)}</section>
 <section className="card"><h3>A shared plan you can take outside.</h3><p>The GitHub app opens without an account. A partner link carries a complete snapshot of the layout, dates, notes and completed rows. It opens without replacing an existing saved plan.</p><p><strong>Snapshots do not update live.</strong> Your partner can tick rows and share the updated copy back. For a single continually synced plan, a shared storage service will be needed.</p><div className="button-row"><button onClick={share}>Copy partner link</button><button onClick={()=>download(plan,'plot-3k-plan.json')}>Export backup</button><button onClick={()=>file.current?.click()}>Import backup</button></div>{shared&&<button onClick={()=>{if(confirm('Save this snapshot over the Plot 3K plan on this device? Export your current plan first if needed.')){setShared(false);window.history.replaceState(null,'',location.pathname);setNotice('Snapshot saved as the plan on this device.');}}}>Save snapshot on this device</button>}<input ref={file} type="file" accept=".json,application/json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>200000)throw Error('Too large');const p=validatePlan(JSON.parse(await f.text()));commit(p);setStorageSafe(true);setNotice('Backup imported. Review any layout warnings.');}catch{setNotice('Import failed: choose a valid Plot 3K backup. Your plan was not changed.');}e.target.value='';}}/>{legacy&&<><p>Your old Plot 3P data is still stored separately on this device.</p><button onClick={()=>{const raw=localStorage.getItem('plot-3p-plan-v2');if(raw)download(JSON.parse(raw),'plot-3p-archive.json');}}>Export old Plot 3P plan</button></>}</section>
 <section className="card"><h3>Planting priorities</h3><p>Dense, repeated blocks come first. Use supplier spacing, with taller crops towards the outer edges and southern end where possible. Low herbs and roots belong near the central plank. A tall northern border would cast shade down the plot.</p><p>Keep perennial clumps and dahlia positions together and reserve them across seasons. Use annual blocks for rotations and successive sowings. The starter layout is a proposal, not a record of existing plants.</p><p>The two beds provide {(2*bw*plan.plot.length/10000).toFixed(2)} m² of growing space. All 27 purchased varieties do not need to be planted at once. Select favourite blocks and use the remaining seeds in later seasons.</p></section>
 <section className="card"><h3>What changed from Plot 3P</h3><p>The rectangular row planner replaces the triangle-specific shade optimiser and individual-plant dragging. Numbered blocks, separate row and plant spacing, zoom, permanent reservations and a planting checklist now form the main workflow.</p><p>The existing crop library is retained alongside the exact purchased varieties. Every purchased variety links to its supplier. Unverified legacy crop values and planning estimates are labelled.</p></section></div>}
 </>}
 {guide&&<div className="modal-backdrop" onClick={()=>setGuide('')}><section ref={modal} role="dialog" aria-modal="true" aria-label="Plant growing guide" className="modal" onClick={e=>e.stopPropagation()}><button autoFocus className="close" onClick={()=>setGuide('')}>Close ×</button><GrowGuide seed={BY_ID[guide]}/></section></div>}
 <footer>Plot 3K · 50% cut flowers / 50% vegetables & herbs · Growing guides checked September 2026</footer></main>;
}
