import purchased from './seed-catalog.json';
import { CROPS } from './planner';
export type Seed = typeof purchased[number];
export const SEEDS: Seed[] = [...purchased, ...CROPS.filter(c=>!['chives','broccoli','dill','zinnia','dahlia','poppy','sunflower','okra','beetroot'].includes(c.id)).map(c=>({id:'library-'+c.id,name:c.name,side:c.group==='flower'?'flowers':'food',life:c.perennial?'Perennial':'Annual',spacing:Math.round(c.spacing*100),rowSpacing:Math.round(c.spacing*100),height:Math.round(c.height*100),months:c.months,method:'Check seed packet',depth:'Check seed packet',germination:'Check seed packet',days:String(c.days),sources:[],notes:'Existing general crop library: spacing and season are planning estimates. Check your cultivar’s packet before sowing.',packets:0,seedCount:null,position:c.sun==='full'?'Full sun':'Full or part sun',checked:'Legacy library'}))];
export const BY_ID = Object.fromEntries(SEEDS.map(c=>[c.id,c]));
export type Block = {id:string;cropId:string;side:'west'|'east';x:number;y:number;width:number;length:number;spacing:number;rowSpacing:number;direction:'length'|'across';status:'planned'|'sown'|'planted'|'finished';permanent:boolean;locked:boolean;date:string;notes:string;doneRows:number[]};
export type Plan = {version:3;plot:{width:number;length:number;path:number;flowers:'west'|'east'};blocks:Block[];updated:string;notes:string};
export const initialPlan:Plan={version:3,plot:{width:220,length:540,path:20,flowers:'west'},blocks:[],updated:'',notes:''};
export function bedWidth(p:Plan){return (p.plot.width-p.plot.path)/2;}
export function rowLayout(b:Block){const across=b.direction==='length'?b.width:b.length;const along=b.direction==='length'?b.length:b.width;const rows=Math.max(0,Math.floor((across+1e-7)/b.rowSpacing));const perRow=Math.max(0,Math.floor((along+1e-7)/b.spacing));return {rows,perRow,count:rows*perRow};}
export function points(b:Block){const {rows,perRow}=rowLayout(b);return Array.from({length:rows},(_,r)=>Array.from({length:perRow},(_,i)=>({row:r,x:b.x+(b.direction==='length'?(r+.5)*b.rowSpacing:(i+.5)*b.spacing),y:b.y+(b.direction==='length'?(i+.5)*b.spacing:(r+.5)*b.rowSpacing)}))).flat();}
export function overlaps(a:Block,b:Block){return a.side===b.side&&a.x<b.x+b.width-.01&&a.x+a.width>b.x+.01&&a.y<b.y+b.length-.01&&a.y+a.length>b.y+.01;}
export function blockErrors(b:Block,p:Plan){const issues:string[]=[];if(b.x<0||b.y<0||b.x+b.width>bedWidth(p)+.01||b.y+b.length>p.plot.length+.01)issues.push('Outside the growing bed');if(p.blocks.some(o=>o.id!==b.id&&o.status!=='finished'&&b.status!=='finished'&&overlaps(b,o)))issues.push('Overlaps another active block');if(!rowLayout(b).count)issues.push('No plants fit at this spacing');return issues;}
export function makeBlock(cropId:string,p:Plan):Block|null{const c=BY_ID[cropId];if(!c)return null;const side=c.side==='flowers'?p.plot.flowers:(p.plot.flowers==='west'?'east':'west');const bw=bedWidth(p);const width=c.method==='Tuber'?c.spacing:Math.min(bw,Math.max(c.rowSpacing,Math.floor((c.rowSpacing<=bw/2?bw/2:bw)/c.rowSpacing)*c.rowSpacing));const length=c.method==='Tuber'?c.spacing:Math.max(c.spacing,Math.ceil(60/c.spacing)*c.spacing);const permanent=/perennial/i.test(c.life);const outer=c.height>=80;const x=side==='west'?(outer?0:bw-width):(outer?bw-width:0);const base:Block={id:crypto.randomUUID(),cropId,side,x,y:0,width,length,spacing:c.spacing,rowSpacing:c.rowSpacing,direction:'length',status:'planned',permanent,locked:false,date:'',notes:'',doneRows:[]};
// Tall blocks start at the southern end; low blocks start near the northern end.
const ys=Array.from({length:Math.floor((p.plot.length-length)/5)+1},(_,i)=>i*5);if(outer||permanent)ys.reverse();for(const y of ys){const b={...base,y};if(!blockErrors(b,p).length)return b;}return null;}
export function validatePlan(value:unknown):Plan{if(!value||typeof value!=='object')throw Error('Not a plan');const p=value as Plan;if(p.version!==3||!p.plot||!Array.isArray(p.blocks)||p.blocks.length>150)throw Error('Choose a Plot 3K backup');for(const [key,min,max] of [['width',100,1000],['length',100,2000],['path',5,150]] as const){if(!Number.isFinite(p.plot[key])||p.plot[key]<min||p.plot[key]>max)throw Error('Invalid plot measurements');}if(p.plot.path>=p.plot.width-40||!['west','east'].includes(p.plot.flowers))throw Error('Invalid bed layout');const ids=new Set();for(const b of p.blocks){if(!b||typeof b.id!=='string'||ids.has(b.id)||!BY_ID[b.cropId])throw Error('Invalid plant block');ids.add(b.id);for(const k of ['x','y','width','length','spacing','rowSpacing'] as const){if(!Number.isFinite(b[k])||b[k]<0||b[k]>2000)throw Error('Invalid block measurements');}if(b.spacing<5||b.rowSpacing<5||b.width<5||b.length<5||!['west','east'].includes(b.side)||!['length','across'].includes(b.direction)||!['planned','sown','planted','finished'].includes(b.status)||typeof b.notes!=='string'||b.notes.length>3000||typeof b.date!=='string'||!Array.isArray(b.doneRows)||b.doneRows.some(r=>!Number.isInteger(r)||r<0||r>400))throw Error('Invalid block details');}if(p.blocks.reduce((n,b)=>n+rowLayout(b).count,0)>10000)throw Error('Plan contains too many planting positions');if(typeof p.notes!=='string'||p.notes.length>10000)throw Error('Invalid notes');return p;}
export function shareEncode(p:Plan){const bytes=new TextEncoder().encode(JSON.stringify(p));return btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
export function shareDecode(s:string){if(s.length>150000)throw Error('Shared plan is too large');return validatePlan(JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0)))));}
